CREATE TABLE beneficiary_details (
    beneficiary_id UUID PRIMARY KEY,
    beneficiary_short_name VARCHAR(50) NOT NULL,
    customer_id VARCHAR(32) NOT NULL,
    beneficiary_type VARCHAR(20) NOT NULL,
    beneficiary_account_type VARCHAR(50),
    first_name VARCHAR(128),
    last_name VARCHAR(128),
    comp_name VARCHAR(128),
    account_number VARCHAR(32) NOT NULL,
    bene_bank_name VARCHAR(128) NOT NULL,
    bene_bank_bic VARCHAR(16) NOT NULL,
    corres_bank_bic_1 VARCHAR(16),
    corres_bank_name_1 VARCHAR(128),
    corres_bank_account_1 VARCHAR(32),
    corres_bank_bic_2 VARCHAR(16),
    corres_bank_name_2 VARCHAR(128),
    corres_bank_account_2 VARCHAR(32),
    bene_acc_number_iban VARCHAR(34),
    max_limit_amount INTEGER,
    max_limit_number_of_transfers INTEGER,
    bene_status VARCHAR(16),
    approval_status VARCHAR(16),
    created_on TIMESTAMP,
    updated_on TIMESTAMP,
    email VARCHAR(64),
    phone_number VARCHAR(15),
    national_id VARCHAR(15),
    date_of_birth DATE,
    date_of_incorp DATE,
    address_line1 VARCHAR(128),
    address_line2 VARCHAR(128),
    city VARCHAR(16),
    state VARCHAR(16),
    country_code VARCHAR(16),
    postal_code VARCHAR(15)
);
